spring:
  profiles:
    active: develop
  atasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jeesite
    username: root
    password: 123456

server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
